In [1]:
pos_high = ['Excellent','Extravagant', 'Great', 'Awesome','Good','inspiring']

In [2]:
weight = 0

In [3]:
pos_medium = []

In [4]:
pos_low = ['pasty']

In [5]:
rating = 1

In [6]:
import pandas as pd

# Creating a pandas dataframe from reviews.txt file
data = pd.read_json('part1.json', lines=True)
data.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A10000012B7CGYKOMPQ4L,000100039X,Adam,"[0, 0]",Spiritually and mentally inspiring! A book tha...,5,Wonderful!,1355616000,"12 16, 2012"
1,A2S166WSCFIFP5,000100039X,"adead_poet@hotmail.com ""adead_poet@hotmail.com""","[0, 2]",This is one my must have books. It is a master...,5,close to god,1071100800,"12 11, 2003"
2,A1BM81XB4QHOA3,000100039X,"Ahoro Blethends ""Seriously""","[0, 0]",This book provides a reflection that you can a...,5,Must Read for Life Afficianados,1390003200,"01 18, 2014"
3,A1MOSTXNIO5MPJ,000100039X,Alan Krug,"[0, 0]",I first read THE PROPHET in college back in th...,5,Timeless for every good and bad time in your l...,1317081600,"09 27, 2011"
4,A2XQ5LZHTD4AFT,000100039X,Alaturka,"[7, 9]",A timeless classic. It is a very demanding an...,5,A Modern Rumi,1033948800,"10 7, 2002"

In [7]:
data.loc[data['overall'] <= 1]

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
80,A9WX8DK93SN5,000100039X,"Ibrahim ""A former Muslim""","[2, 9]",As Amin Rihani described his own friend Gibran...,1,"Pasty, pasty! Too much!",1385683200,"11 29, 2013"
121,A3HLNFF21USD1K,000100039X,"Maureen A. Wilkie ""mo in michigan""","[0, 56]",I appreciate getting the book at the great pri...,1,adequate,1219708800,"08 26, 2008"
146,A14A2VLURI8DGP,000100039X,Raymond Evangelista,"[0, 27]","This man was a son of a pastor, but worshipped...",1,"Read your Bible, not this book!",1361318400,"02 20, 2013"
148,AD6E4Y092Y4KP,000100039X,reader,"[1, 7]","You've got to be kidding, all you 5 star revie...",1,"Pompous, Pretentious, Platitudes",1392336000,"02 14, 2014"
159,ALD1CRUBY1365,000100039X,R. L. MILLER,"[53, 130]",This book was a philosophical touchstone for i...,1,Deceptively pseudo-scriptural,1022025600,"05 22, 2002"
...,...,...,...,...,...,...,...,...,...
51971,AK3R3RNUWLFJR,0029146739,solar-bear,"[30, 88]",I chanced upon this book years ago in the libr...,1,Them damn Asians are spoiling my KKK world order!,1116547200,"05 20, 2005"
51973,A34EUGHCTY2HMR,0029146739,S. Ryan,"[40, 109]","This book is so historically myopic, that I ha...",1,So have all the dumb whites and dumb Asians be...,1119657600,"06 25, 2005"
51974,APHPSNW6WTJW,0029146739,Sylvia Lawrence,"[11, 24]",I had the chance to thoroughly examine the Men...,1,"Oh, please, the author used the useless WAIS test",1221868800,"09 20, 2008"
51975,A2AZHXLKJL11R5,0029146739,"T. barca ""Aspasia Blue""","[9, 53]",I just have one question. Why is it that the T...,1,Tuskegee Airmen -- I just have one question.,1180310400,"05 28, 2007"
51978,A2MFH7EB3GIHJU,0029146739,"""timothy1146""","[18, 59]",There is little disputing the statistics cited...,1,Overrated rehashings,1007251200,"12 2, 2001"

In [13]:
def check(text):
    for lines in text:
        if any(word in lines for word in pos_high):
            rating = 50
    return rating

In [14]:
text=data.reviewText[0:]

In [15]:
check(text)

50

In [17]:
rating

1

In [ ]:
def applyAll(text):
    if any(x in text for x in pos_high):
        rating = 5
    elif any(x in text for x in pos_medium):
        rating = 3
    elif any(x in text for x in pos_low):
        rating = 1 
    else:
        print('No rating')

In [ ]:
applyAll(data.reviewText)

In [ ]:
print(rating)

In [ ]:
rating